# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hiram Construction 
email: hiramconstructionzw@gmail.com
phone: +263 778 481 291
address: 160 Gilchrist Rd, Marlbrough, Harare, Zimbabwe
rel-author: Trust Madende
description: Hiram Construction a zimbabwean based construction company specialising in building construction, electrical, and civil engineering works.
baseurl: "/hiram construction"
url: "http://hiramconstruction.co.zw"


twitter_path: https://twitter.com/hiramconstruct1
facebook_path: https://facebook.com/hiramzw
linkedin_path: https://linkedin.com/company/hiramconstruction
instagram_path: https://www.instagram.com/hiramconstructionzw




# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
sass:
  sass_dir: assets/css
  style: :nested



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
